declare namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_CLIENT_URI: string;
    REACT_APP_SERVER_URI: string;
    REACT_APP_GOOGLE_CLIENT_ID: string;
    REACT_APP_LOCAL_ID: string;
    REACT_APP_LOCAL_TOKEN: string;
    REACT_APP_ROUTE_LAYOUT: string;
    REACT_APP_ROUTE_NOT_FOUND: string;
    REACT_APP_ROUTE_SIGN_IN: string;
    REACT_APP_ROUTE_SIGN_UP: string;
    REACT_APP_ROUTE_EMAIL: string;
    REACT_APP_ROUTE_EMAIL_CONFIRM: string;
    REACT_APP_ROUTE_PASSWORD_FORGOT: string;
    REACT_APP_ROUTE_PASSWORD_RESET: string;
    REACT_APP_ROUTE_ADMIN: string;
    REACT_APP_ROUTE_ALBUM: string;
    REACT_APP_ROUTE_ALBUM_PARAM_ID: string;
    REACT_APP_ROUTE_PLAYLIST: string;
    REACT_APP_ROUTE_PLAYLIST_PARAM_ID: string;
    REACT_APP_ROUTE_PROFILE: string;
    REACT_APP_ROUTE_PROFILE_PARAM_ID: string;
    REACT_APP_ROUTE_PROFILE_FAVORITES: string;
    REACT_APP_ROUTE_PROFILE_TRACKS: string;
    REACT_APP_ROUTE_PROFILE_SUBSCRIBERS: string;
    REACT_APP_ROUTE_PROFILE_SUBSCRIPTIONS: string;
    REACT_APP_ROUTE_SEARCH: string;
    REACT_APP_ROUTE_TRACK: string;
    REACT_APP_ROUTE_TRACK_PARAM_ID: string;
    REACT_APP_ROUTE_UPLOAD: string;
    REACT_APP_ROUTE_UPLOAD_TRACK: string;
    REACT_APP_ROUTE_UPLOAD_ALBUM: string;
  }
}
